crypt: main.cpp proc.cpp rsa.cpp el.cpp shamir.cpp tests.cpp mbig.cpp
	g++ -o mcrypt main.cpp proc.cpp rsa.cpp el.cpp shamir.cpp tests.cpp mbig.cpp

clean:
	rm -f rsa_encrypt
	rm -f rsa_decrypt
	rm -f el_encrypt
	rm -f el_decrypt
